runtime: nodejs20
service: default
env: standard

handlers:
  - url: /
    static_files: index.html
    upload: index.html # for GET and POST requests

  - url: /style.css
    static_files: style.css
    upload: style.css # for GET and POST requests

  - url: /main.js
    static_files: main.js
    upload: main.js # for GET and POST requests

  - url: /images
    static_dir: images
